name: Recipe Suggestion Rag API 
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker hub
      run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ vars.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: docker build . --file Dockerfile --tag ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DH_REPO_NAME }}:latest

